#-------------------------------------------------------------------------------
# appveyor.yml
# Author: Alan D. Snow, 2017
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#System specifications for Appveyor
#-------------------------------------------------------------------------------
environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      MINICONDA: "C:\\Miniconda-x64"
    - PYTHON_VERSION: "3.5"
      MINICONDA: "C:\\Miniconda3-x64"
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda3-x64"

install:
  - 'SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%'
  - conda config --set always_yes yes
  - conda update -q conda python
#-----------------------------------------------------------------------------
# Create conda environment for gazar
#-----------------------------------------------------------------------------
  - conda create -n gazar python=%PYTHON_VERSION%
  - activate gazar
  - conda env update -f=conda_env.yml
  # restart environment
  - deactivate gazar
  - activate gazar
#-------------------------------------------------------------------------------
# Install gazar
#-------------------------------------------------------------------------------
  - 'cd %APPVEYOR_BUILD_FOLDER%'
  - pip install -e .[tests]

build: false

test_script:
  - py.test --cov-report term-missing --cov=gazar
  - flake8 --ignore=F401 gazar setup.py tests
  - pylint gazar
