# conda-env.yml
# Configuration file for creating a Conda Environment with dependencies needed for gazar.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f conda_env.yml

name: gazar
channels:
- conda-forge
- defaults
dependencies:
- affine
- appdirs
- gdal=2.2
- pyproj
- utm
